import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion, useMotionValue, useScroll, useSpring, useTransform } from 'framer-motion';
import { ArrowRight, Bell, CalendarDays, ChartSpline, Check, Clock, Scissors, ShieldCheck, Sparkles, Stethoscope, Store, UserRound, UsersRound, WandSparkles } from 'lucide-react';
import './styles.css';

type CardProps = { children: React.ReactNode; className?: string; id?: string };
const fade = { hidden: { opacity: 0, y: 28, filter: 'blur(14px)' }, show: { opacity: 1, y: 0, filter: 'blur(0px)' } };
const Section = ({ children, className = '', id }: CardProps) => <section id={id} className={`mx-auto w-full max-w-7xl px-6 py-24 md:px-10 ${className}`}>{children}</section>;
const Reveal = ({ children, className = '' }: CardProps) => <motion.div variants={fade} initial="hidden" whileInView="show" viewport={{ once: true, margin: '-120px' }} transition={{ duration: .8, ease: [0.16, 1, 0.3, 1] }} className={className}>{children}</motion.div>;

function Navbar() {
  const { scrollY } = useScroll();
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => scrollY.on('change', y => setScrolled(y > 24)), [scrollY]);
  return <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-500 ${scrolled ? 'py-3' : 'py-6'}`}><nav className={`mx-auto flex max-w-7xl items-center justify-between rounded-full px-5 py-3 transition-all duration-500 ${scrolled ? 'border border-white/60 bg-white/75 shadow-card backdrop-blur-2xl' : 'bg-transparent'}`}>
    <a className="flex items-center gap-3 font-semibold tracking-tight" href="#"><span className="grid h-9 w-9 place-items-center rounded-full bg-ink text-white shadow-card">A</span>Aera</a>
    <div className="hidden items-center gap-8 text-sm text-zinc-600 md:flex"><a href="#features">Features</a><a href="#businesses">Businesses</a><a href="#pricing">Pricing</a><a href="#contact">Contact</a></div>
    <a className="magnetic rounded-full bg-ink px-5 py-2.5 text-sm font-medium text-white shadow-card" href="#contact">Get Started</a>
  </nav></header>;
}

function HeroDashboard({ mx, my }: { mx: any; my: any }) {
  const x = useTransform(mx, [0, 1], [-18, 18]); const y = useTransform(my, [0, 1], [-14, 14]);
  return <motion.div style={{ x, y }} className="relative mx-auto w-full max-w-[620px] rounded-[2rem] border border-white/80 bg-white/80 p-3 shadow-soft backdrop-blur-2xl">
    <div className="rounded-[1.5rem] border border-line bg-[#fbfcfe] p-4"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs text-muted">Today</p><h3 className="text-xl font-semibold">Operations command</h3></div><span className="rounded-full bg-blue/10 px-3 py-1 text-xs font-medium text-blue">Live</span></div>
    <div className="grid gap-3 md:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl bg-white p-4 shadow-card"><div className="mb-3 flex items-center justify-between"><b>July 2026</b><CalendarDays size={18}/></div><div className="grid grid-cols-7 gap-2 text-center text-xs text-muted">{'MTWTFSS'.split('').map(d=><span key={d}>{d}</span>)}{Array.from({length:28}).map((_,i)=><span key={i} className={`rounded-xl py-2 ${[7,12,16,21].includes(i)?'bg-ink text-white':'bg-zinc-50'}`}>{i+1}</span>)}</div></div>
    <div className="space-y-3"><Metric label="Revenue" value="$18.4k" trend="+24%"/><Metric label="Bookings" value="126" trend="+18%"/><div className="rounded-3xl bg-ink p-4 text-white"><p className="text-xs text-white/60">Next</p><p className="mt-1 font-medium">Maya Reed — Color treatment</p><p className="mt-3 text-xs text-white/60">10:30 AM · Chair 2</p></div></div></div>
    <div className="mt-3 grid gap-3 md:grid-cols-3"><Mini title="CRM" icon={<UsersRound/>}/><Mini title="Reminders" icon={<Bell/>}/><Mini title="Analytics" icon={<ChartSpline/>}/></div></div>
    <motion.div animate={{ y: [-8, 8, -8] }} transition={{ duration: 6, repeat: Infinity }} className="absolute -left-8 top-24 hidden rounded-2xl border border-white bg-white/90 p-3 shadow-card backdrop-blur md:block"><p className="text-xs text-muted">SMS verified</p><p className="font-medium">Booking confirmed</p></motion.div>
    <motion.div animate={{ y: [10, -10, 10] }} transition={{ duration: 7, repeat: Infinity }} className="absolute -right-6 bottom-24 hidden rounded-2xl border border-white bg-white/90 p-3 shadow-card backdrop-blur md:block"><p className="text-xs text-muted">No-show risk</p><p className="font-medium text-blue">Reduced 32%</p></motion.div>
  </motion.div>;
}
const Metric=({label,value,trend}:{label:string;value:string;trend:string})=><div className="rounded-3xl bg-white p-4 shadow-card"><p className="text-xs text-muted">{label}</p><div className="flex items-end justify-between"><b className="text-2xl">{value}</b><span className="text-xs text-blue">{trend}</span></div></div>;
const Mini=({title,icon}:{title:string;icon:React.ReactNode})=><div className="rounded-2xl bg-white p-4 shadow-card"><div className="mb-2 text-blue">{React.cloneElement(icon as React.ReactElement,{size:18})}</div><b className="text-sm">{title}</b><p className="mt-1 text-xs text-muted">Synced instantly</p></div>;

function App(){ const mx=useMotionValue(.5), my=useMotionValue(.5); const sx=useSpring(mx,{stiffness:80,damping:20}); const sy=useSpring(my,{stiffness:80,damping:20});
 const businesses=[['Salon',Scissors],['Barber Shop',Store],['Dental Clinic',ShieldCheck],['Spa',Sparkles],['Medical Clinic',Stethoscope],['Tattoo Studio',WandSparkles]];
 const features=['Smart Calendar','CRM','Appointment Scheduling','Automatic Reminders','Customer History','Business Analytics','Staff Management','Service Management','Availability Management','Notifications'];
 return <main onMouseMove={e=>{mx.set(e.clientX/window.innerWidth);my.set(e.clientY/window.innerHeight)}} className="min-h-screen overflow-hidden bg-[#f7f8fb] text-ink"><Navbar/><section className="relative grid min-h-screen place-items-center px-6 pb-20 pt-32"><div className="aura"/><div className="mx-auto grid max-w-7xl items-center gap-14 md:grid-cols-[.9fr_1.1fr]"><motion.div initial="hidden" animate="show" variants={{show:{transition:{staggerChildren:.12}}}}><motion.p variants={fade} className="mb-5 inline-flex rounded-full border border-line bg-white/70 px-4 py-2 text-sm text-muted shadow-card backdrop-blur">Enterprise-grade scheduling for appointment-led businesses</motion.p><motion.h1 variants={fade} className="max-w-3xl text-6xl font-semibold tracking-[-.055em] md:text-8xl">Manage every appointment from one place.</motion.h1><motion.p variants={fade} className="mt-7 max-w-xl text-xl leading-8 text-muted">Aera automates bookings, schedules, reminders, and customer management so you can focus on growing your business.</motion.p><motion.div variants={fade} className="mt-9 flex gap-4"><a className="magnetic rounded-full bg-blue px-7 py-4 font-medium text-white shadow-card" href="#contact">Get Started <ArrowRight className="inline" size={18}/></a><a className="rounded-full border border-line bg-white px-7 py-4 font-medium shadow-card" href="#demo">Watch Demo</a></motion.div></motion.div><HeroDashboard mx={sx} my={sy}/></div></section>
 <Section id="businesses"><Reveal><h2 className="section-title">Built for businesses where time is the product.</h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-3">{businesses.map(([b,I]:any)=><Reveal key={b} className="group rounded-4xl border border-white bg-white/75 p-7 shadow-card backdrop-blur transition hover:-translate-y-1 hover:shadow-soft"><I className="text-blue"/><h3 className="mt-8 text-2xl font-semibold">{b}</h3><p className="mt-3 text-muted">A polished booking experience for teams, staff, and customers.</p></Reveal>)}</div></Section>
 <Section><div className="grid gap-6 md:grid-cols-2"><Reveal className="rounded-4xl border border-red-100 bg-white p-8 shadow-card"><p className="text-sm text-muted">Before Aera</p><h2 className="mt-3 text-4xl font-semibold tracking-tight">Appointment chaos.</h2>{['Missed appointments','Constant WhatsApp messages','Paper calendars','Scheduling conflicts','Operational stress'].map(x=><p className="mt-4 flex gap-3 text-muted" key={x}><Clock className="text-zinc-400"/> {x}</p>)}</Reveal><Reveal className="rounded-4xl bg-ink p-8 text-white shadow-soft"><p className="text-sm text-white/55">With Aera</p><h2 className="mt-3 text-4xl font-semibold tracking-tight">One automated system.</h2>{['Verified customer booking','Real-time team calendar','Automatic reminders','Clean CRM history','Actionable insights'].map(x=><p className="mt-4 flex gap-3 text-white/75" key={x}><Check className="text-blue"/> {x}</p>)}</Reveal></div></Section>
 <Section><Reveal><h2 className="section-title">A calmer way to book.</h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-4">{['Enter phone number','Receive SMS code','Book appointment','Business receives reservation instantly'].map((s,i)=><Reveal key={s} className="rounded-4xl border border-line bg-white p-7 shadow-card"><span className="text-sm text-blue">Step {i+1}</span><h3 className="mt-8 text-2xl font-semibold">{s}</h3></Reveal>)}</div></Section>
 <Section><Reveal className="rounded-[2.5rem] bg-white p-4 shadow-soft md:p-8"><HeroDashboard mx={sx} my={sy}/></Reveal></Section>
 <Section id="features"><Reveal><h2 className="section-title">Everything appointment businesses need. Nothing they don't.</h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-5">{features.map(f=><Reveal key={f} className="rounded-3xl border border-line bg-white p-6 shadow-card"><Sparkles className="text-blue" size={20}/><h3 className="mt-6 font-semibold">{f}</h3></Reveal>)}</div></Section>
 <Section><div className="grid gap-4 md:grid-cols-5">{['Spend less time answering messages','Reduce no-shows','Increase bookings','Deliver a professional experience','Grow with clarity'].map(b=><Reveal key={b} className="rounded-4xl bg-white p-7 shadow-card"><h3 className="text-xl font-semibold">{b}</h3><p className="mt-4 text-sm leading-6 text-muted">Replace manual coordination with a system customers trust and teams enjoy using.</p></Reveal>)}</div></Section>
 <Section><div className="grid gap-4 md:grid-cols-3">{['Aera made our salon feel like a premium brand overnight.','We stopped losing bookings in messages and calls.','The CRM gives us context before every client walks in.'].map((t,i)=><Reveal key={t} className="rounded-4xl border border-line bg-white p-8 shadow-card"><p className="text-xl leading-8">“{t}”</p><p className="mt-8 text-sm text-muted">Founder, {['Luma Studio','Northline Dental','Ink & Ritual'][i]}</p></Reveal>)}</div></Section>
 <Section id="contact" className="text-center"><Reveal><h2 className="mx-auto max-w-4xl text-5xl font-semibold tracking-[-.04em] md:text-7xl">Turn every booking into a beautifully managed experience.</h2><a className="magnetic mt-10 inline-flex rounded-full bg-ink px-8 py-4 font-medium text-white shadow-soft" href="mailto:hello@aera.app">Get Started</a></Reveal></Section><footer className="border-t border-line px-6 py-10 text-center text-sm text-muted">© 2026 Aera. Appointment scheduling and CRM, engineered for calm growth.</footer></main> }
createRoot(document.getElementById('root')!).render(<App/>);
